# Site settings
title: Whitehat Safe Harbor
description: "A project dedicated to establishing legal protections for ethical hackers."
baseurl: "" # Leave empty since your site is at the root of your domain
url: "https://daimon-law.github.io/whitehat-safe-harbor" # No trailing slash

# Build settings
theme: minimal # If using a GitHub-supported theme, you can often just use the theme's short name
plugins:
  - jekyll-feed

# Exclude files from being processed or published on the site
exclude:
  - LICENSE
  - .gitignore
  - CNAME
